import type { Realm } from './types'

export const mockRealms: Realm[] = [
	{
		id: 'realm-bank-mobile',
		code: 'bank-mobile',
		name: 'Bank Mobile',
		description: 'Realm для host-приложения мобильного банка.',
		status: 'ACTIVE',
		miniappsCount: 12,
		publishedMiniappsCount: 9,
		clientsCount: 2,
		activeSessionsCount: 184,
		createdAt: '2026-05-01T08:00:00.000Z',
		updatedAt: '2026-05-10T12:30:00.000Z',
		metadata: {
			ownerTeam: 'Bank Mobile Platform',
			environment: 'production',
			region: 'ru-central-1',
			authMode: 'SSO',
			allowedOrigins: [
				'https://bank.example.com',
				'https://mobile.bank.example.com',
			],
			clientId: 'bank-mobile-backend',
			scopes: ['miniapp:catalog', 'miniapp:launch', 'session:logout'],
		},
	},
	{
		id: 'realm-telecom-app',
		code: 'telecom-app',
		name: 'Telecom App',
		description: 'Realm для telecom host-приложения.',
		status: 'ACTIVE',
		miniappsCount: 7,
		publishedMiniappsCount: 5,
		clientsCount: 1,
		activeSessionsCount: 76,
		createdAt: '2026-05-03T10:20:00.000Z',
		updatedAt: '2026-05-09T15:10:00.000Z',
		metadata: {
			ownerTeam: 'Telecom Digital',
			environment: 'stage',
			region: 'ru-central-1',
			authMode: 'SSO',
			allowedOrigins: ['https://telecom.example.com'],
			clientId: 'telecom-app-backend',
			scopes: ['miniapp:catalog', 'miniapp:launch'],
		},
	},
	{
		id: 'realm-fintech-demo',
		code: 'fintech-demo',
		name: 'Fintech Demo',
		description: 'Demo Realm для тестирования SDK и SSO flow.',
		status: 'DISABLED',
		miniappsCount: 3,
		publishedMiniappsCount: 0,
		clientsCount: 1,
		activeSessionsCount: 0,
		createdAt: '2026-05-06T12:20:00.000Z',
		updatedAt: '2026-05-08T11:45:00.000Z',
		metadata: {
			ownerTeam: 'Fintech Lab',
			environment: 'demo',
			region: 'ru-central-1',
			authMode: 'SSO',
			allowedOrigins: ['https://demo.fintech.example.com'],
			clientId: 'fintech-demo-backend',
			scopes: ['miniapp:catalog', 'miniapp:launch', 'statistics:read'],
		},
	},
]
