export { CreateRealmPage } from './create/ui/CreateRealmPage'
export { RealmDetailsPage } from './details/ui/RealmDetailsPage'
export { RealmsPage } from './list/ui/RealmsPage'
export { RoleMappingPage } from './role-mapping/ui/RoleMappingPage'
export { RealmRolesPage } from './roles/ui/RealmRolesPage'
